
# config file for target positions
# file is linked to targetPositioning node 	
# each vektor has 4 parameters: x, y, w, z
# use x, y for target position 
# use w, z for orientation when goal reached



angelika: [4.109, -2.352, 1.0, 0.0]

daniel: [5.013, -3.687, 1.0, 0.0] 

simon: [5.84, -4.582, 1.0, 0.0]

lukas: [6.798, -5.744, 1.0, 0.0]


