
# config file for target positions
# file is linked to targetPositioning node 	
# each vektor has 4 parameters: x, y, w, z
# use x, y for target position 
# use w, z for orientation when goal reached (Quaternion)


angelika: [-6.280, 0.217,  -0.061, 0.998]

daniel: [-7.966, -0.909, -0.003, 1.00]

simon: [10.849, -2.954, 0.976, 0.218]

lukas: [-9.267, 1.119, -0.127, 0.992]


