
# config file for target positions
# file is linked to targetPositioning node 	
# each vektor has 4 parameters: x, y, w, z
# use x, y for target position 
# use w, z for orientation when goal reached (Quaternion)


angelika: [-3.985, 0.247,  0.988, -0.154,]

daniel: [-0.872, 2.219, 0.575, -0.818,]

simon: [0.403, 0.230, -0.005, 1.00]

lukas: [-2.289, -1.869, 0.775, 0.632]


